#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Commands\DatabaseSeedingCommand;
use Commands\WorkerCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new DatabaseSeedingCommand());
$application->add(new WorkerCommand());
$application->run();